"""
Generates PLACEHOLDER historical resolved-thread data, shaped like the real
Kaggle Customer-Support-on-Twitter export, so the pipeline is runnable and
testable before the real dataset is plugged in.

*** THIS IS SYNTHETIC DATA, NOT THE REAL DATASET. ***
Swap data/historical_threads.csv for a real AmazonHelp subsample before
generating final results. See README "Using the real dataset" section.
"""
import pandas as pd
import random

random.seed(7)

SAMPLES = [
    ("@AmazonHelp hey where's my package? order #113-4482910, says shipped 3 days ago",
     "Hi there, sorry for the wait! I can see your order is currently in transit and on track for delivery tomorrow. Track it live here: [link] -Priya",
     "order_status_tracking"),
    ("@AmazonHelp can you tell me the delivery status of order 112-9981234? tracking hasn't updated in 2 days",
     "Hello! Tracking can lag behind the carrier scan by up to 24-48hrs even when the package is moving. Your order is still on schedule for the original delivery date. -Raj",
     "order_status_tracking"),
    ("@AmazonHelp when will my order arrive? no tracking info showing up at all",
     "Hi, thanks for flagging! Tracking info can take up to 24hrs to populate after a label is created. If nothing shows by tomorrow, DM us your order # and we'll dig in. -Meera",
     "order_status_tracking"),
    ("@AmazonHelp is my stuff still coming today? app says out for delivery since 8am",
     "Hi! Out-for-delivery status usually means it'll arrive by end of day. If it's not there by 9pm local time, let us know and we'll open a trace. -Priya",
     "order_status_tracking"),
    ("@AmazonHelp order status pls, been 4 days since dispatch and still says preparing for shipment",
     "Sorry about the delay in the status update! I've checked and your item has actually left the warehouse -- the app just hasn't synced. New ETA is Thursday. -Raj",
     "order_status_tracking"),
    ("@AmazonHelp my package says delivered but I never got it!! nothing on my porch, checked with neighbors",
     "I'm really sorry to hear that. Since the carrier marked it delivered but you don't have it, please DM your order # -- we'll open an investigation and can issue a replacement or refund once confirmed. -Meera",
     "delivery_delay_or_lost"),
    ("@AmazonHelp order is now 6 days late, prime said 2-day shipping, what's going on",
     "Apologies for missing the delivery estimate -- this is on us. I've applied a partial refund of the shipping fee and expedited a re-ship. Tracking incoming via DM. -Priya",
     "delivery_delay_or_lost"),
    ("@AmazonHelp carrier tracking hasn't moved in 5 days, is my package lost?",
     "That does look stuck -- sorry! I've opened a trace with the carrier. If there's no update within 48hrs we'll send a free replacement, no need to wait for the trace to close. -Raj",
     "delivery_delay_or_lost"),
    ("@AmazonHelp still no package, estimated date was yesterday, this is the 2nd time this month",
     "I completely understand the frustration, especially with this happening again. I've escalated this to our logistics team and issued a full refund for this order as a goodwill gesture. -Meera",
     "delivery_delay_or_lost"),
    ("@AmazonHelp where is my package, tracking says 'delayed', no new date given",
     "Sorry for the vague update! I've pulled the latest from the carrier -- new expected date is Monday. If it slips again please come back to us and we'll step in directly. -Priya",
     "delivery_delay_or_lost"),
    ("@AmazonHelp received my blender today and it's completely shattered, box was fine but item inside is broken",
     "Oh no, sorry about that! I've started a free replacement, no return needed for this one -- just dispose of the damaged item safely. New one ships today. -Raj",
     "damaged_or_wrong_item"),
    ("@AmazonHelp ordered a black keyboard, got sent a pink mouse instead?? order #114-2231",
     "Sorry for the mix-up! That's definitely the wrong item. I've sent the correct keyboard out today and generated a free return label for the mouse -- no rush to send it back first. -Meera",
     "damaged_or_wrong_item"),
    ("@AmazonHelp shoes arrived with a huge tear on the side, clearly used not new",
     "That's not okay, I'm sorry. I've processed a full refund and you're welcome to keep or discard the item -- no return required given the condition. -Priya",
     "damaged_or_wrong_item"),
    ("@AmazonHelp phone case cracked right out of the box, terrible packaging",
     "Sorry to hear that! I've set up a replacement shipment with reinforced packaging this time, should arrive in 2 days. -Raj",
     "damaged_or_wrong_item"),
    ("@AmazonHelp got someone else's order entirely, different name on the packing slip too",
     "Apologies, that's a fulfillment error on our end. I've cancelled the refund/return path and am shipping your correct order today at no charge, plus a prepaid label for the wrong item. -Meera",
     "damaged_or_wrong_item"),
    ("@AmazonHelp requested a refund 10 days ago, still haven't received the money back",
     "Sorry for the delay! I checked and your refund was processed on our end 6 days ago -- bank processing can take 3-5 extra business days. If it's not there in 2 more days, DM us and we'll investigate directly with the bank. -Priya",
     "refund_or_return"),
    ("@AmazonHelp how do I return this jacket, doesn't fit, still has tags on",
     "No problem! Go to Your Orders > select the item > Return or Replace Items, choose 'Doesn't fit' -- you'll get a prepaid label instantly. -Raj",
     "refund_or_return"),
    ("@AmazonHelp refund shows as 'processing' for a week now, order was cancelled by amazon itself",
     "Apologies for the wait -- since this was a seller-side cancellation, I've manually pushed the refund through on our end, should reflect in 3-5 business days. -Meera",
     "refund_or_return"),
    ("@AmazonHelp can I get a refund instead of a replacement, don't want the item anymore",
     "Absolutely, I've converted your replacement request to a refund -- it'll be issued to your original payment method within 3-5 business days. -Priya",
     "refund_or_return"),
    ("@AmazonHelp returned item 2 weeks ago per tracking, no refund yet, this is ridiculous",
     "I'm sorry for how long this has taken. I can see the return was received. I've manually issued your refund right now rather than waiting on the automated process. -Raj",
     "refund_or_return"),
    ("@AmazonHelp need to cancel order 115-8827 right now, ordered wrong size by mistake",
     "I've cancelled that order for you -- since it hadn't shipped yet, no charge will go through. Feel free to reorder the right size anytime! -Meera",
     "cancellation_request"),
    ("@AmazonHelp how do I cancel my prime membership, don't want the renewal charge",
     "You can cancel anytime via Account > Prime Membership > End Membership. If you'd like, I can also do this for you now -- just confirm and I'll process it. -Priya",
     "cancellation_request"),
    ("@AmazonHelp order already shipped but I want to cancel, can you stop it",
     "Since it's already shipped, we can't intercept it in transit, but you can refuse delivery or return it once it arrives for a full refund. Want me to set that up now? -Raj",
     "cancellation_request"),
    ("@AmazonHelp accidentally ordered 2 of the same thing, cancel one please order 116-002",
     "Done! I've cancelled the duplicate order -- you won't be charged for it. The original order is unaffected. -Meera",
     "cancellation_request"),
    ("@AmazonHelp subscribe and save order keeps auto-renewing, I want to cancel the subscription",
     "I've cancelled the recurring subscription on that item -- this was the last shipment, no further charges will be made. -Priya",
     "cancellation_request"),
    ("@AmazonHelp locked out of my account, reset password link isn't arriving in my email",
     "Sorry about that! Please check your spam folder first -- if it's not there, DM us the email on file (not here publicly) and we'll manually trigger a reset. -Raj",
     "account_or_login_issue"),
    ("@AmazonHelp someone logged into my account and placed an order I didn't make!!",
     "This needs immediate attention -- please change your password right now and DM us your order number. We'll secure the account and reverse any unauthorized charges. -Meera",
     "account_or_login_issue"),
    ("@AmazonHelp 2FA code never arrives, can't get into my account for 2 days now",
     "Sorry for the trouble! DM us and we'll verify your identity through an alternate method and get 2FA reset on our end. -Priya",
     "account_or_login_issue"),
    ("@AmazonHelp account shows suspended for no reason, I haven't done anything wrong",
     "I understand the concern -- account holds are usually tied to a specific flag we can review. Please DM your account email and we'll look into lifting it. -Raj",
     "account_or_login_issue"),
    ("@AmazonHelp can't merge my two accounts, orders are split between them",
     "Account merges need identity verification for security reasons -- please DM us both account emails and we'll start that process. -Meera",
     "account_or_login_issue"),
    ("@AmazonHelp charged twice for the same order, can see two identical charges on my card",
     "Sorry for the confusion! One of those is likely an authorization hold that will drop off in a few days, but I've double-checked and confirmed only one actual charge went through. -Priya",
     "billing_or_payment_issue"),
    ("@AmazonHelp promo code didn't apply at checkout even though it was valid",
     "Apologies for that! I've manually applied the discount amount as account credit to your next order. -Raj",
     "billing_or_payment_issue"),
    ("@AmazonHelp payment failed but I was still charged, order shows as not placed",
     "Sorry about that! Failed-payment holds sometimes still show on your statement temporarily -- they auto-release in 3-5 business days since the order wasn't actually placed. -Meera",
     "billing_or_payment_issue"),
    ("@AmazonHelp gift card balance not showing up even though I redeemed it yesterday",
     "Sorry for the delay -- gift card balances can take up to 24hrs to reflect. If it's still missing after that, DM us the gift card code and we'll credit it manually. -Priya",
     "billing_or_payment_issue"),
    ("@AmazonHelp charged full price but item was on sale when I ordered, price protection?",
     "I checked and you're right -- I've refunded the price difference to your original payment method. -Raj",
     "billing_or_payment_issue"),
    ("@AmazonHelp does this coffee maker come with a warranty? can't find it on the listing",
     "Hi! Most kitchen appliances come with a 1-year manufacturer warranty -- you can find warranty specifics under 'Product Guides and Documents' on the listing page. -Meera",
     "general_product_question"),
    ("@AmazonHelp is this laptop compatible with an external monitor, listing doesn't say",
     "Great question -- most laptops in this line support HDMI or USB-C external displays, but I'd recommend checking the exact model's spec sheet in the listing's technical details for certainty. -Priya",
     "general_product_question"),
    ("@AmazonHelp what's the difference between the two versions of this vacuum listed",
     "The two versions typically differ in battery capacity and attachments included -- check the comparison table under 'Compare with similar items' on the listing for the exact breakdown. -Raj",
     "general_product_question"),
    ("@AmazonHelp will this fit a queen size bed, description is unclear",
     "Good catch, listings can be ambiguous! I'd recommend checking the dimensions in the product details section against your mattress size before ordering. -Meera",
     "general_product_question"),
    ("@AmazonHelp is this product safe for kids, no age recommendation listed",
     "For safety-specific questions like this, I'd recommend checking the manufacturer's product safety info or contacting them directly, since we can't make safety certifications ourselves. -Priya",
     "general_product_question"),
    ("@AmazonHelp this is the THIRD time I'm messaging about this, nobody is helping me, I want a manager NOW",
     "I'm really sorry for the repeated frustration -- this should not have taken this long. I'm escalating you directly to a senior specialist who will take ownership end-to-end. DM incoming. -Meera",
     "complaint_escalation"),
    ("@AmazonHelp absolutely done with amazon, cancelling prime, reporting this to consumer protection",
     "I completely understand your frustration and I'm sorry we let you down. I'd like the chance to make this right -- please DM us and I'll personally handle your case from here. -Priya",
     "complaint_escalation"),
    ("@AmazonHelp your customer service bot keeps looping me, I need an actual human being to help",
     "Sorry for the runaround -- you've got one now. Please DM your order number and I'll personally see this through. -Raj",
     "complaint_escalation"),
    ("@AmazonHelp this is unacceptable, my elderly mother was charged for something she never ordered",
     "I'm very sorry to hear this -- this needs urgent attention. Please DM the order details and we will investigate and reverse any unauthorized charge immediately. -Meera",
     "complaint_escalation"),
    ("@AmazonHelp filing a chargeback if this isn't resolved today, been going back and forth for weeks",
     "I hear you and I'm sorry it's dragged on this long. I'm taking direct ownership of this now -- DM me your case/order number and I'll resolve it today. -Priya",
     "complaint_escalation"),
    ("@AmazonHelp check out my new mixtape link in bio", None, "other_spam_irrelevant"),
    ("@AmazonHelp lol remember when this app crashed during prime day 2019", None, "other_spam_irrelevant"),
    ("@AmazonHelp does anyone else think the new logo looks weird", None, "other_spam_irrelevant"),
    ("@AmazonHelp free followers giveaway click here", None, "other_spam_irrelevant"),
    ("@AmazonHelp lmaooo this thread is unrelated but funny", None, "other_spam_irrelevant"),
]

rows = []
for i, (tweet, reply, intent) in enumerate(SAMPLES):
    rows.append({
        "thread_id": f"synthetic_{i:04d}",
        "customer_tweet": tweet,
        "historical_agent_reply": reply if reply else "",
        "intent": intent,
    })

df = pd.DataFrame(rows)
df.to_csv("data/historical_threads.csv", index=False)
print(f"Wrote {len(df)} placeholder threads -> data/historical_threads.csv")
print(df["intent"].value_counts())
